include ../../../config.mk

HPPDEPS = clark-y.hpp naca4.hpp

all:

install:
	mkdir -p $(PREFIX)/include/vortexje/shapes/airfoils
	cp $(HPPDEPS) $(PREFIX)/include/vortexje/shapes/airfoils

clean:
	rm -f *.o
