include ../../config.mk

HPPDEPS = gmsh-surface-loader.hpp

all:

install:
	mkdir -p $(PREFIX)/include/vortexje/surface-loaders
	cp $(HPPDEPS) $(PREFIX)/include/vortexje/surface-loaders

clean:
	rm -f *.o
